---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
    listen 443 ssl http2;
    server_name localhost;
    root /var/www/html;
    index index.html index.htm;

    ssl_certificate             /etc/nginx/ssl/tls.crt;
    ssl_certificate_key         /etc/nginx/ssl/tls.key;

    location / {
    root   /var/www/html;
    index  index.html index.htm;
    }

    }


    server {
    listen       80;
    server_name  localhost;

    location / {
    root   /var/www/html;
    index  index.html index.htm;
    }

    }

  index.html: |
    <html>
    <h1>Welcome</h1>
    </br>
    <h1>This is a my test site </h1>
    </html
