apiVersion: v1
kind: Pod
metadata:
  name: top-secret-pod
spec:
  containers:
  - name: secret-pod
    image: nginx
    env:
      - name: MY_USERNAME
        valueFrom:
          secretKeyRef:
            name: topsecret
            key: username
      - name: MY_PASS
        valueFrom:
          secretKeyRef:
            name: topsecret
            key: password
  restartPolicy: Never
