apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- toYaml .Values.labels.jenkins | nindent 4 }}
spec:
  type: {{ .Values.service.jenkins.type }}
  ports:
    - port: {{ .Values.service.jenkins.port }}
      targetPort: {{ .Values.endpoint.jenkins }}
      protocol: TCP
      name: web
  selector:
    {{- toYaml .Values.labels.jenkins | nindent 4 }}
