---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-netology
  namespace: default
  labels:
    app: netology
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netology
  template:
    metadata:
      labels:
        app: netology
    spec:
      containers:
      - name: nginx-netology
        image: nginx
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: "/etc/nginx/conf.d"
          readOnly: true
        - name: index
          mountPath: "/var/www/html"
          readOnly: true
        env:
          - name: WEB_SITE
            valueFrom:
              configMapKeyRef:
                name: web
                key: mysite
      volumes:
      - name: config
        configMap:
          name: nginx-config
          items:
            - key: default.conf
              path: default.conf
      - name: index
        configMap:
          name: nginx-config
          items:
            - key: index.html
              path: index.html

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-netology
  namespace: default
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: nginx-netology
