---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
    listen       8080;
    server_name  nginx-netology;
    location / {
    root   /var/www/html;
    index  index.html index.htm;
    }
    }

  index.html: |
    <html>
    <h1>Hello</h1>
    </br>
    <h1>This is a Netology site </h1>
    </html
