{
 "title": "Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Idle %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(avg by (instance) (rate(node_cpu_seconds_total{instance=\"nodeexporter:9100\", job=\"nodeexporter\", mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "CPU Load average",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "CPU LA1" },
    { "expr": "node_load5", "legendFormat": "CPU LA5" },
    { "expr": "node_load15", "legendFormat": "CPU LA15" }
   ]
  },
  {
   "title": "Filesystem Size Free",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{fstype!~\"tmpfs|fuse.lxcfs|squashfs\"} / node_filesystem_size_bytes{fstype!~\"tmpfs|fuse.lxcfs|squashfs\"}*100",
     "legendFormat": "/dev/vda2"
    }
   ]
  },
  {
   "title": "Memory Free",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - node_memory_Inactive_bytes/node_memory_MemAvailable_bytes*100",
     "legendFormat": "ram"
    }
   ]
  }
 ]
}